@echo off

echo Stopping Redis...
taskkill /F /IM redis-server.exe > nul
echo Stopping memcached...
taskkill /F /IM memcached.exe > nul
echo Stopping nginx...
taskkill /F /IM nginx.exe > nul
echo Stopping PHP FastCGI...
taskkill /F /IM php-cgi.exe > nul

echo Starting...

startService.bat